In [ ]:
import torch
import numpy as np
import torch.nn as nn
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


bc = datasets.load_breast_cancer()
x,y = bc.data,bc.target

n_samples,n_features = x.shape
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=4321)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train = torch.from_numpy(x_train.astype(np.float32))
x_test = torch.from_numpy(x_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

y_train = y_train.view(y_train.shape[0],1)
y_test = y_test.view(y_test.shape[0],1)

class LogisticRegression(nn.Module):
  def __init__(self,n_input_features):
      super(LogisticRegression,self).__init__()
      self.linear = nn.Linear(n_input_features,1)
  
  def forward(self,x):
    y_predicted = torch.sigmoid(self.linear(x))
    return y_predicted


model = LogisticRegression(n_features)
criterion = nn.BCELoss()
learning_rate = 0.01
optimiser = torch.optim.SGD(model.parameters(),lr=learning_rate)
num_epoch = 1000

for epoch in range(num_epoch):
  y_predicted = model(x_train)
  loss = criterion(y_predicted,y_train)
  loss.backward()
  optimiser.step()

with torch.no_grad():
  y_predicted = x_test
  y_predicted_cls = y_predicted.round
  
print(bc.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
